# include: package:pedantic/analysis_options.1.11.0.yaml
# include: package:strict/analysis_options.yaml
include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false